on: push

permissions:
    contents: write

jobs:
    npm-build:
        runs-on: ubuntu-latest
        
        steps:
        - uses: actions/checkout@v4
        
        - run: |
            npm install
            npm install --save-dev @babel/plugin-proposal-private-property-in-object
            npm run build
        
        - uses: JamesIves/github-pages-deploy-action@v4
          with:
            branch: gh-pages
            folder: build
